import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import type { Request } from "express";
import { logger } from "./logger";

const SECRET_FILE = path.join(os.tmpdir(), "portal-cel-e2e-bypass-secret");

let cachedSecret: string | null = null;

function isProduction(): boolean {
  return (process.env.NODE_ENV ?? "").toLowerCase() === "production";
}

export function isE2ETestModeEnabled(): boolean {
  return process.env.E2E_TEST_MODE === "1" && !isProduction();
}

function ensureSecret(): string | null {
  if (!isE2ETestModeEnabled()) return null;
  if (cachedSecret) return cachedSecret;
  try {
    if (fs.existsSync(SECRET_FILE)) {
      const existing = fs.readFileSync(SECRET_FILE, "utf8").trim();
      if (existing.length >= 32) {
        cachedSecret = existing;
        return cachedSecret;
      }
    }
    const fresh = crypto.randomBytes(32).toString("hex");
    fs.writeFileSync(SECRET_FILE, fresh, { mode: 0o600 });
    try {
      fs.chmodSync(SECRET_FILE, 0o600);
    } catch {
      /* best effort */
    }
    cachedSecret = fresh;
    logger.info(
      { secretFile: SECRET_FILE },
      "E2E test-mode bypass secret provisioned (dev/test only)",
    );
    return cachedSecret;
  } catch (err) {
    logger.error({ err }, "Failed to provision E2E bypass secret");
    return null;
  }
}

const LOOPBACK_ADDRS = new Set<string>([
  "127.0.0.1",
  "::1",
  "::ffff:127.0.0.1",
]);

function isLoopback(req: Request): boolean {
  const candidates = [
    req.ip,
    (req.socket as { remoteAddress?: string } | undefined)?.remoteAddress,
  ];
  return candidates.some((a) => !!a && LOOPBACK_ADDRS.has(a));
}

/**
 * Returns true only when ALL of the following hold:
 *  - NODE_ENV is not production
 *  - process.env.E2E_TEST_MODE === "1"
 *  - the request arrived on a loopback socket (same container only)
 *  - the request carries `x-e2e-secret` matching the on-disk secret that
 *    was generated by this api-server process at boot. The secret is not
 *    in git, not in env vars, and not echoed in any HTTP response; only
 *    processes in the same container can read it from /tmp.
 *
 * Any failed check returns false, and normal Clerk auth runs unchanged.
 */
export function isE2EBypassRequest(req: Request): boolean {
  if (!isE2ETestModeEnabled()) return false;
  if (!isLoopback(req)) return false;
  const provided = req.header("x-e2e-secret");
  if (!provided) return false;
  const expected = ensureSecret();
  if (!expected) return false;
  if (provided.length !== expected.length) return false;
  try {
    return crypto.timingSafeEqual(
      Buffer.from(provided),
      Buffer.from(expected),
    );
  } catch {
    return false;
  }
}

// Eagerly provision the secret at module load so the file is present
// before any test runs. No-op in production.
ensureSecret();
