import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import meRouter from "./me";
import teamRouter from "./team";
import projectRouter from "./project";
import notificationRecipientsRouter from "./notificationRecipients";
import kanbanRouter from "./kanban";
import adminKanbanRouter from "./adminKanban";
import milestonesRouter from "./milestones";
import adminMilestonesRouter from "./adminMilestones";
import documentsRouter from "./documents";
import decisionsRouter from "./decisions";
import adminDecisionsRouter from "./adminDecisions";
import calendarRouter from "./calendar";
import adminRouter from "./admin";
import adminAllowedDomainsRouter from "./adminAllowedDomains";
import adminApprovalsRouter from "./adminApprovals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(meRouter);
router.use(teamRouter);
router.use(projectRouter);
router.use(notificationRecipientsRouter);
router.use(kanbanRouter);
router.use(adminKanbanRouter);
router.use(milestonesRouter);
router.use(adminMilestonesRouter);
router.use(documentsRouter);
router.use(decisionsRouter);
router.use(adminDecisionsRouter);
router.use(calendarRouter);
router.use(adminRouter);
router.use(adminAllowedDomainsRouter);
router.use(adminApprovalsRouter);

export default router;
