// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/desarrollo-tecnico/AnexoTabs.tsx": () => import("../components/mockups/desarrollo-tecnico/AnexoTabs.tsx"),
  "./components/mockups/desarrollo-tecnico/DocsPortal.tsx": () => import("../components/mockups/desarrollo-tecnico/DocsPortal.tsx"),
  "./components/mockups/desarrollo-tecnico/HubLanzadera.tsx": () => import("../components/mockups/desarrollo-tecnico/HubLanzadera.tsx")
};
